// Dashboard and decision-view CSS, extracted verbatim from the previous inline
// <style> blocks (SUB-02 readability refactor). Presentation only: no selector
// here reads state, and nothing here decides anything.

export const DASHBOARD_STYLES = `:root{--ink:#1c1b18;--paper:#fbf9f4;--rule:#d9d3c5;--pass:#1f6b3a;--veto:#9b2c1f;--mute:#6b665c;--accent:#2a4d7a}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 Georgia,"Times New Roman",serif;overflow-x:hidden}
main{max-width:64rem;margin:0 auto;padding:2rem 1.25rem 4rem}h1,h2,h3,h4{font-family:"Helvetica Neue",Arial,sans-serif;letter-spacing:-.01em;margin:0 0 .5rem}
h1{font-size:2rem}h2{font-size:1.4rem;margin-top:2.5rem;border-top:1px solid var(--rule);padding-top:1.25rem}h3{font-size:1.1rem;margin-top:1.5rem}h4{font-size:1rem;margin:0}
code,td.num,.figure code{font-family:"SF Mono",Consolas,"Liberation Mono",monospace;font-size:.92em}code{word-break:break-all}
.eyebrow{font-family:Arial,sans-serif;font-size:.72rem;text-transform:uppercase;letter-spacing:.12em;color:var(--mute)}
.stamp{font-family:Arial,sans-serif;font-size:.75rem;padding:.15rem .5rem;border:1px solid currentColor;border-radius:2px;text-transform:uppercase}
.stamp--pass,.stamp--filled{color:var(--pass)}.stamp--veto,.stamp--unresolved{color:var(--veto)}.stamp--resting,.stamp--released{color:var(--accent)}
.self{font-family:Arial,sans-serif;font-size:.85rem;color:var(--mute);border:1px solid var(--rule);padding:.75rem 1rem;margin:1rem 0}
.self strong{color:var(--ink)}.degraded{color:var(--veto)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(11rem,1fr));gap:.75rem;margin:1rem 0}
.tile{border:1px solid var(--rule);padding:.75rem 1rem;background:#fff}.tile .eyebrow{display:block;margin-bottom:.25rem}.tile strong{display:block;font-size:1.35rem;font-family:"SF Mono",Consolas,monospace}.tile small{display:block;color:var(--mute)}
table{border-collapse:collapse;width:100%;font-size:.9rem;margin:.75rem 0;display:block;overflow-x:auto}th,td{text-align:left;padding:.35rem .5rem;border-bottom:1px solid var(--rule);vertical-align:top}th{font-family:Arial,sans-serif;font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:var(--mute)}td.num{text-align:right}
.result--proposal{color:var(--accent)}.result--no_trade{color:var(--mute)}
.gate-rail{list-style:none;display:grid;grid-template-columns:repeat(auto-fit,minmax(7rem,1fr));gap:.4rem;padding:0;margin:.75rem 0}
.gate{border:1px solid var(--rule);padding:.4rem .5rem;background:#fff;font-family:Arial,sans-serif;font-size:.78rem}.gate span{display:block;color:var(--mute)}.gate strong{display:block}.gate small{display:block;color:var(--mute);word-break:break-word}
.gate--pass strong{color:var(--pass)}.gate--veto{border-color:var(--veto)}.gate--veto strong{color:var(--veto)}
.candidate,.lifecycle,.cycle{border:1px solid var(--rule);background:#fff;padding:1rem 1.25rem;margin:1rem 0}.candidate header,.lifecycle header{display:flex;gap:.75rem;align-items:baseline;flex-wrap:wrap}
.rationale{font-style:italic;margin:.5rem 0}.chain{margin:0}.chain div{display:grid;grid-template-columns:8rem minmax(0,1fr);gap:.5rem;padding:.35rem 0;border-top:1px dotted var(--rule)}.chain dt{font-family:Arial,sans-serif;font-size:.78rem;text-transform:uppercase;color:var(--mute)}.chain dd{margin:0}
.golden{counter-reset:none;padding-left:0;list-style:none}.golden li{padding:.3rem 0;border-bottom:1px dotted var(--rule)}
.disclaimer{font-size:.85rem;color:var(--mute);margin-top:3rem;border-top:1px solid var(--rule);padding-top:1rem}
.discrepancies li{color:var(--veto)}`;

export const DECISION_VIEW_STYLES = `:root{--paper:#f3f6f4;--ink:#132019;--muted:#52635a;--rule:#b9c5be;--pass:#176347;--pass-wash:#dcece4;--veto:#963d2e;--veto-wash:#f3dfda;--panel:#fbfcfb;--shadow:rgba(18,42,29,.08);--font-body:"Segoe UI","Helvetica Neue",sans-serif;--font-data:"Cascadia Code","SFMono-Regular",Consolas,monospace}
*{box-sizing:border-box}html{-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;background:var(--paper);color:var(--ink)}body{margin:0;font:16px/1.6 var(--font-body)}main{width:min(1480px,calc(100% - 48px));margin:0 auto;padding:64px 0 96px}.masthead{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:32px;align-items:end;padding-bottom:24px;border-bottom:2px solid var(--ink)}.eyebrow{margin:0 0 8px;font:700 12px/1.2 var(--font-data);letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}h1,h2{margin:0;text-wrap:balance}h1{max-width:18ch;font-size:clamp(40px,7vw,88px);line-height:.95;letter-spacing:-.05em}h2{font-size:24px;line-height:1.2}.masthead__note{max-width:38ch;margin:0;color:var(--muted);text-wrap:pretty}.tape-meta{display:flex;flex-wrap:wrap;gap:8px 24px;margin:20px 0 48px;padding:0;list-style:none;font:600 14px/1.4 var(--font-data);font-variant-numeric:tabular-nums}.decisions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.decision{min-width:0;padding:32px;background:var(--panel);box-shadow:0 1px 2px var(--shadow),0 8px 24px var(--shadow)}.decision--pass{border-top:8px solid var(--pass)}.decision--veto{border-top:8px solid var(--veto)}.decision__title{display:flex;align-items:center;justify-content:space-between;gap:16px}.stamp{padding:6px 10px;font:800 13px/1 var(--font-data);letter-spacing:.1em}.decision--pass .stamp{background:var(--pass-wash);color:var(--pass)}.decision--veto .stamp{background:var(--veto-wash);color:var(--veto)}.rationale{max-width:60ch;min-height:52px;margin:24px 0;color:var(--muted);text-wrap:pretty}dl{display:grid;gap:0;margin:0 0 32px;border-top:1px solid var(--rule)}dl>div{display:grid;grid-template-columns:160px 1fr;gap:16px;padding:12px 0;border-bottom:1px solid var(--rule)}dt{color:var(--muted)}dd{margin:0;font-family:var(--font-data);font-variant-numeric:tabular-nums}.gate-rail{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;margin:0;padding:0;list-style:none}.gate{display:grid;grid-template-rows:auto auto 1fr;min-height:120px;padding:12px;background:var(--paper)}.gate>span,.gate>strong{font-family:var(--font-data)}.gate>span{font-size:12px;color:var(--muted)}.gate>strong{font-size:14px}.gate>small{margin-top:12px;font-size:12px;line-height:1.35;color:var(--muted);overflow-wrap:anywhere}.gate--pass>strong{color:var(--pass)}.gate--veto{background:var(--veto-wash)}.gate--veto>strong{color:var(--veto)}footer{margin-top:48px;padding-top:16px;border-top:1px solid var(--rule);color:var(--muted);font-size:14px}
@media(max-width:960px){main{width:min(100% - 32px,720px);padding-top:32px}.masthead,.decisions{grid-template-columns:1fr}.rationale{min-height:0}}@media(max-width:560px){main{width:min(100% - 24px,520px)}.decision{padding:20px}.decision__title,dl>div{grid-template-columns:1fr;display:grid}.stamp{justify-self:start}.gate-rail{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
