"""Regenerate REPO_MAP.md and TEST_MAP.md from the working tree.

Run by the pre-commit hook (hooks/pre-commit); maps are generated, never
hand-edited. Python is a tooling-only dependency here — the product code is
TypeScript (CONCEPT §5).
"""
from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", "node_modules", "dist", ".tmp", ".vercel"}
SKIP_FILES = {"REPO_MAP.md", "TEST_MAP.md"}
TEST_MARKERS = (".test.", ".spec.", "_test.")


def tracked_or_new_files() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    files = []
    for line in out.splitlines():
        p = Path(line)
        if any(part in SKIP_DIRS for part in p.parts) or p.name in SKIP_FILES:
            continue
        files.append(p)
    return sorted(files)


def describe(path: Path) -> str:
    """First heading / docstring / comment line of a file, as a one-liner."""
    try:
        text = (ROOT / path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    for line in text.splitlines()[:10]:
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
        if s.startswith(('"""', "'''")):
            return s.strip("\"'").strip()
        if s.startswith(("//", "/*")):
            return s.lstrip("/* ").strip()
    return ""


def write_maps() -> None:
    files = tracked_or_new_files()
    repo_lines = [
        "# REPO_MAP — auto-generated by tools/generate_map.py, do not edit",
        "",
    ]
    for f in files:
        desc = describe(f)
        repo_lines.append(f"- `{f.as_posix()}`" + (f" — {desc}" if desc else ""))
    (ROOT / "REPO_MAP.md").write_text("\n".join(repo_lines) + "\n", encoding="utf-8")

    tests = [f for f in files if any(m in f.name for m in TEST_MARKERS)]
    test_lines = [
        "# TEST_MAP — auto-generated by tools/generate_map.py, do not edit",
        "",
    ]
    if tests:
        test_lines += [f"- `{f.as_posix()}`" for f in tests]
    else:
        test_lines.append(
            "No test files yet — the first ones arrive with the pure core "
            "(red-first, per CONCEPT §3)."
        )
    (ROOT / "TEST_MAP.md").write_text("\n".join(test_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write_maps()
    print("REPO_MAP.md and TEST_MAP.md regenerated.")
